version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_prod
    ports:
      - "5432:5432"
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    restart: always
    env_file:
      - .env

volumes:
  postgres_data:



